version: "3.8"

networks:
  net:
    external: true

services:
  app:
    container_name: challenge-rabbitmq-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - net
    volumes:
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test
      - ./package.json:/usr/src/app/package.json
      - ./nest-cli.json:/usr/src/app/nest-cli.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./tsconfig.build.json:/usr/src/app/tsconfig.build.json
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=info
      - LOG_TYPE=pino-pretty
      - DEBUG_MODE=false
    command: ["pnpm", "start:dev"]

    stdin_open: true
    tty: true

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    env_file:
      - ./.env
    networks:
      - net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
