# docker-compose.prod.yml
version: "3.8"

services:
  app:
    container_name: challenge-rabbitmq-prod
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
      LOG_LEVEL: info
      LOG_TYPE: pino
      DEBUG_MODE: "false"
      PORT: 3000
      GRAFANA_URL: http://loki:3100/loki/api/v1/push
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
      loki:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    restart: unless-stopped
    volumes:
      - loki-data:/loki

  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    restart: unless-stopped
    depends_on:
      - loki

volumes:
  loki-data:
  grafana-data:
