version: "3.8"

services:
  app:
    container_name: challenge-rabbitmq-debug
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "9229:9229"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - LOG_TYPE=pino-pretty
      - DEBUG_MODE=true
    command: ["pnpm", "start:debug"]
    volumes:
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test
      - ./package.json:/usr/src/app/package.json
      - ./nest-cli.json:/usr/src/app/nest-cli.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./tsconfig.build.json:/usr/src/app/tsconfig.build.json
    stdin_open: true
    tty: true
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
